### ISSUE TITLE
手机端提交不了form表单到服务器

### ISSUE THREAD

**Issue by mqy1023** [CommanderXL/imgResize#1]
您好！我这边剪切后的图片是base64格式的，手机端将图片数据转为Blob对象，使用FormData上传文件，但是很多手机无法将Blob对象是注入到FormData对象当中的。所有提交不了，请求有什么解决方案吗？谢谢

**Comment by CommanderXL** [comment]
既然你这边都已经转为`base64`格式了，事实上就可以通过`ajax`直接把`base64`给传到后端去完成图片的上传了。

`Blob对象`确实在安卓部分手机里面存在兼容性的问题，所以为了避开这个问题，我在实际的处理过程当中都是使用`base64`这个方式去上传图片的。

**Comment by mqy1023** [comment]
base64字符串就长了，这个后端要用什么类型去存它的，怎么处理的

**Comment by CommanderXL** [comment]
我现在的做法是将`base64`拿到后转为图片，然后将图片上传到静态存储服务器上，静态存储服务器会返回一个图片的路径。直接通过这个路径就能访问到你所上传的图片。

**Comment by mqy1023** [comment]
后端转为图片文件？转成blob对象？还是？

**Comment by CommanderXL** [comment]
直接转成图片文件，然后完成上传到静态存储服务器

**Comment by mqy1023** [comment]
好的，谢谢

**Comment by mqy1023** [comment]
base64图片字符串太长了，java的string都接受不了全部

**Comment by mqy1023** [comment]
是base64字符串传到后端的时候，传过去和接受到的字符对不上，这个后端怎么处理？还是前端要特殊处理一下字符串

**Comment by CommanderXL** [comment]
你是用的我封装的那个包吗？

**Comment by mqy1023** [comment]
不是，我动态插入html的，不能用$  .onchange来监听。我用canvas去转成base64的图片的

**Comment by CommanderXL** [comment]
那你说的接收到的字符匹配不上是什么意思？ 字符串给截断了？

**Comment by CommanderXL** [comment]
你是用`formdata`还是直接`ajax`把`base64`塞到`body`里面上传的？

**Comment by mqy1023** [comment]
放到formdata里面的，不知道是不是base64字符串中各种空格特殊字符传输出错了

**Comment by mqy1023** [comment]
img.src.replace("data:image/png;base64,","");  问题找到了，要把前缀去掉
